# Generated by Django 4.0 on 2021-12-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='if_not_way',
            field=models.TextField(blank=True, default='c', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='purchased_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
