# Generated by Django 4.0 on 2021-12-22 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_payment_if_not_way_payment_purchased_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='name',
        ),
    ]
