# Generated by Django 4.0 on 2021-12-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_volunteer_volunteer_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightout',
            name='trip_date',
            field=models.DateTimeField(),
        ),
    ]
