# Generated by Django 4.0 on 2021-12-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_nightout_trip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='describe',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='students',
            name='explain_way',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='students',
            name='talents_and_level',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='where_would_you_want_to_volunteer',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
