# Generated by Django 4.0 on 2021-12-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_students_describe_alter_students_explain_way_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='describe',
        ),
        migrations.RemoveField(
            model_name='students',
            name='do_you_have_experience',
        ),
        migrations.RemoveField(
            model_name='students',
            name='explain_way',
        ),
        migrations.RemoveField(
            model_name='students',
            name='where_would_you_want_to_volunteer',
        ),
    ]
