# Generated by Django 4.0 on 2021-12-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_students_describe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nightout',
            name='trip_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purchased_date',
            field=models.DateField(auto_now=True),
        ),
    ]
