# Generated by Django 4.0 on 2022-01-04 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_staff_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('describe', models.CharField(max_length=200)),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='myapp.volunteer')),
            ],
        ),
    ]
