# Generated by Django 4.0 on 2022-01-04 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_studentvolunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentvolunteer',
            name='volunteer2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='volunteer2', to='myapp.volunteer'),
        ),
    ]
