# Generated by Django 4.0 on 2022-01-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_studentvolunteer_volunteer2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='if_not_way',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
