# Generated by Django 4.0 on 2022-01-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_payment_if_not_way'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='talents_and_level',
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
