# Generated by Django 4.0 on 2022-01-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_students_talents_and_level_students_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
