# Generated by Django 4.0 on 2022-01-29 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_event_manager_alter_event_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
                ('time', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='StudentLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('describe', models.CharField(max_length=200)),
                ('lecture1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lecture1', to='myapp.lecture')),
                ('lecture2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='lecture2', to='myapp.lecture')),
            ],
        ),
    ]
