# Generated by Django 4.0 on 2022-01-30 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_lecture_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlecture',
            name='describe',
        ),
    ]
