# Generated by Django 4.0 on 2022-01-30 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_studentlecture_lecture1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlecture',
            name='monday_lecture1',
        ),
        migrations.RemoveField(
            model_name='studentlecture',
            name='monday_lecture2',
        ),
        migrations.AddField(
            model_name='studentlecture',
            name='m1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='m1', to='myapp.lecture'),
        ),
        migrations.AddField(
            model_name='studentlecture',
            name='m2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='m2', to='myapp.lecture'),
        ),
        migrations.AddField(
            model_name='studentlecture',
            name='t1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='t1', to='myapp.lecture'),
        ),
        migrations.AddField(
            model_name='studentlecture',
            name='t2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='t2', to='myapp.lecture'),
        ),
        migrations.AddField(
            model_name='studentlecture',
            name='th1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='th1', to='myapp.lecture'),
        ),
        migrations.AddField(
            model_name='studentlecture',
            name='th2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='th2', to='myapp.lecture'),
        ),
        migrations.AddField(
            model_name='studentlecture',
            name='w1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='w1', to='myapp.lecture'),
        ),
        migrations.AddField(
            model_name='studentlecture',
            name='w2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='w2', to='myapp.lecture'),
        ),
    ]
