# Generated by Django 4.0 on 2022-02-01 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_studentlecture_monday_lecture1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atteendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='myapp.lecture')),
            ],
        ),
    ]
