# Generated by Django 4.0 on 2022-02-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='recipt',
            field=models.ImageField(blank=True, null=True, upload_to='payment/recipets/'),
        ),
    ]
