# Generated by Django 4.0 on 2022-02-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_payment_recipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purchased_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
